Fix issue with getters when inheriting
gertqin/vuex-class-modules pull request #25
Opened 2019-10-03 09:42 UTC by budziam

This PR solves a problem with using getters in inherited classes. Problem is solved by iterating over prototype chain until `VuexModule` class.

2019-10-07 08:02 UTC, budziam commented
@gertqin would you find a moment to review this PR?

2019-10-07 09:08 UTC, bodograumann commented on test/getters-inheritance.ts
> +describe.only("getters-inheritance", () => {
Is that `only` scoped to the module?
I think you should remove it.

2019-10-07 09:11 UTC, bodograumann commented
As you are changing how the prototype chain is handled, maybe we also need tests for the other features in the context of inheritance. Afaics there are none yet.

2019-10-09 08:29 UTC, bodograumann commented
Looks good to me.

2019-10-09 08:35 UTC, budziam commented
You are right it would be nice to add more tests regarding the way prototype chain is handled. As soon as I find time, I'll take care of it

2019-10-09 13:02 UTC, budziam commented
@bodograumann I've added couple tests to cover common uses cases of inheritance.

2019-10-10 13:05 UTC, bodograumann requested changes
That already looks quite good. Could you please also test the use of `super.<method>` in the three test sets?

2019-10-11 14:16 UTC, budziam commented
I decided to create separate test cases for that purpose. Does it suit you?

2019-10-12 07:15 UTC, bodograumann approved these changes
Yes, thank you. This is exactly what we need.

2019-10-12 07:18 UTC, merged

2019-10-13 16:23 UTC, bodograumann commented
The new version 1.1.2 is now on npm.
Thank you very much for your contribution @budziam.